### ISSUE TITLE
uart_read() can not read data and never returns

### ISSUE THREAD

**Issue by wuhanstudio** [riscv-mcu/hbird-sdk#1]
Hello，

发现HBird v1 SDK 的串口读是不是有些小 bug，我试了下 baremetal 里面：

```
/SoC/hbird/Common/Source/Drivers/hbird_uart.c
```

```
int main(void)
{
    while(1)
    {
    	uart_write(UART0, (uart_read(UART0)));
    	printf("Hi");
    }
}
```

串口读不到数据，并且一直卡死在 uart_read() 里无法返回，
论坛里也有不少同学碰到串口无法读数据的问题。

**Comment by wuhanstudio** [comment]
最近打算把 RT-Thread 的控制台 MSH 移植过来，控制台可以正常输出，但是却没法读取，发现卡在了 uart_read()

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15157070/99956846-a0182c00-2d7e-11eb-9b3a-faed0d03ce8e.gif)

hbird-sdk 里移植的 RT-thread 也是只实现了 **rt_hw_console_output()**，没有实现 **rt_hw_console_getchar()**，所以我在想是不是串口读有些问题。

**Comment by fanghuaqi** [comment]
串口读应该没问题，你把波特率设置为57600bps看看，115200bps读取会有点问题，8Mhz主频过低造成的

**Comment by wuhanstudio** [comment]
> 串口读应该没问题，你把波特率设置为57600bps看看，115200bps读取会有点问题，8Mhz主频过低造成的

多谢，确实串口是没问题的，这样 RT-Thread 的 msh 控制台就可以完整使用了 。我刚刚提了一个 PR，增加了一个控制台的 demo。

msh 是 rtt 很受欢迎的组件，你觉得把这个组件加进来作为一个 demo 怎么样 ;)
