### ISSUE TITLE
似乎芯来OpenOCD在原版基础上有修改，能否提供芯来OpenOCD源码呢？

### ISSUE THREAD

**Issue by MonostableLSD** [riscv-mcu/hbird-sdk#4]
用芯来的openocd打出来log发现一直卡在scan()函数，但是在openocd源码里没有这个函数，不知是否可以开源芯来openocd的源码？

**Comment by fanghuaqi** [comment]
https://github.com/riscv-mcu/riscv-openocd

**Comment by MonostableLSD** [comment]
抱歉没仔细找 谢啦！
