### ISSUE TITLE
导入”hbird-sdk-0.1.2“到NucleiStudio报错

### ISSUE THREAD

**Issue by 1030677119** [riscv-mcu/hbird-sdk#5]
![image](https://user-images.githubusercontent.com/33683522/139174510-1812b38d-e356-4135-9b46-5db22793ec72.png)

**Comment by fanghuaqi** [comment]
请直接导入最新的master代码，master里面才包含npk.yml文件

**Comment by fanghuaqi** [comment]
https://doc.nucleisys.com/hbirdv2/quick_start/ide_latest.html
