### ISSUE TITLE
如何在eclipse编译freertos

### ISSUE THREAD

**Issue by ardeal** [riscv-mcu/hbird-sdk#6]
你好，

我在FPGA上跑了RISCV E203。 我现在希望使用eclipse编译freertos，和helloworld，请问，应该如何操作，有相关的教程吗？

我看到这个例子，讲的是如何跑hbird_e_sdk里面的bsp，但是，并没有讲如何跑freertos：
https://blog.csdn.net/weixin_31225753/article/details/113068996

**Comment by fanghuaqi** [comment]
https://doc.nucleisys.com/hbirdv2/quick_start/ide_latest.html

**Comment by ardeal** [comment]
你好，
你这个链接，是将如何在nuclei studio里面创建SDK工程。我看明白了，谢谢！
你这个链接，也没有说到如何跑FreeRTOS的问题。 你有在eclipse里面，编译FreeRTOS的例子、文档吗？

**Comment by fanghuaqi** [comment]
你可以看看例子里面是不是有个freertos的，创建的时候选择即可

**Comment by ardeal** [comment]
好的，谢谢你！

**Comment by ardeal** [comment]
> 你可以看看例子里面是不是有个freertos的，创建的时候选择即可
