### ISSUE TITLE
how to configure and compile FreeRTOS in eclipse?

### ISSUE THREAD

**Issue by ardeal** [riscv-mcu/hbird-sdk#7]
Hi,

I downloaded RISCV E203 to FPGA, and now would like to compile FreeRTOS and download it to E203.
the following link told me about how to compile bsp of hbird_e_sdk in eclipse, but it didn't include how to configure and compile FreeRTOS in eclipse;
https://blog.csdn.net/weixin_31225753/article/details/113068996

is there any doc about how to do it?

**Comment by fanghuaqi** [comment]
https://doc.nucleisys.com/hbirdv2/quick_start/ide_latest.html
